#twillo details for sending alert sms
SID = 'You can find SID in your Twilio Dashboard' 
AUTH_TOKEN = 'You can find  on your Twilio Dashboard' 
FROM_NUMBER = 'This is the no. generated by Twilio. You can find this on your Twilio Dashboard'
TO_NUMBER = 'This is your number. Make sure you are adding +91 in beginning'

#bolt iot details
API_KEY = 'XXXXXXXXX'
   #This is your Bolt cloud API 
Key.  
DEVICE_ID = 'BOLTXXXXXXXXX' #This is the ID of your Bolt device
